apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  application.properties: |
    # Database configuration
    db.host=mongodb
    db.port=27017
    db.name=catalogdb
    db.collection=products

    # API configuration
    api.version=v1
    api.prefix=/api

    # Logging configuration
    logging.level=INFO
    logging.format=json

    feature.inventory=true
