apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nodejs-sample
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:18-ubi8
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-sample:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
  postCommit:
    script: "npm test"